### PR TITLE
Increase vectorization

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR is my attempt to vectorize some of the `for`-loops in `pyunfold/mix.py`

- [x] Tests added / passed
- [x] Passes `flake8 pyunfold`

### CODE REVIEW

**Comment by zhampel** [comment]
Hey @jrbourbeau I like the cleanup of a lot of this you've done. Can you explain how you vectorized some of those nasty loops? I think I put it in the current state back in May, so I haven't thought about these for a while.

**Comment by jrbourbeau** [comment]
Thanks!

> Can you explain how you vectorized some of those nasty loops?

Unfortunately I haven't been able to fully vectorize everything. What's been done here is more along the lines of replacing 3 nested `for`-loops

```python
# (ti, ec_j + tk) elements
for ej, ti, tk in product(range(0, ebins), range(0, cbins), range(0, cbins)):
    ec_j = ej * cbins
    dcdP[ti, ec_j+tk] = -NE_F_R[ej] * Mij[ej, ti] * n_c_prev[tk]
```

with 2 `for`-loops

```python
# (ti, ec_j + tk) elements
tk = np.arange(0, cbins)
for ej in np.arange(0, ebins):
    A = np.outer(-NE_F_R[ej] * Mij[ej, :], n_c_prev)
    for ti in np.arange(0, cbins):
        dcdP[ti, ej * cbins + tk] = A[ti, tk]
```

If you have any suggestions on how we can further reduce the `for`-loops here, they would be very welcomed

**Comment by zhampel** [comment]
Ah ok, so the `tk` array gets rid of one of the for loops. I also thought about this a lot when first implementing this massive matrix, and never got far with further optimizations. However, in the end, we only care about the diagonals of the square of this matrix, so maybe there's something to consider there. I'll need to think about it more, but I think it's a bit much to incorporate with this PR.

**Comment by jrbourbeau** [comment]
> However, in the end, we only care about the diagonals of the square of this matrix, so maybe there's something to consider there

Good point, we can both think about this and hopefully come up with something 

> I'll need to think about it more, but I think it's a bit much to incorporate with this PR.

Sounds good to me. I think we can iterate here towards a more efficient solution. I'll add a changelog entry to this PR and then merge into `master` if that works for you?

**Comment by zhampel** [comment]
Yes, that works for me. I'm assuming you checked the outputs to double triple quadruple check that the calc doesn't change yeah? ;)

**Comment by jrbourbeau** [comment]
There are a few tests in `pyunfold/tests/test_unfold.py`, namely, `test_example`, `test_example_2`, `test_example_non_square_response` that each test the unfolded distributed, systematic, and statistical errors outputted by the current pyunfold with the the same outputs from the original implementation of pyunfold at each iteration. (The saved results from the original implementation of pyunfold are in `pyunfold/pyunfold/tests/test_data/`). I've been using those tests as my "these changes give the same answer" standard. 

I did so _some_ fine grained testing to check that certain sub-calculations were giving the same results.

<details>
<summary>Example</summary>

```python
from itertools import product
import numpy as np
np.random.seed(2)

ebins = 11
cbins = 7
shape = (ebins, cbins)
Mij = np.random.rand(*shape)
n_c_prev = np.random.rand(cbins)
NE_F_R = np.random.rand(ebins)

def original():
    dcdP = np.zeros((cbins, cbins * ebins))
    # (ti, ec_j + tk) elements
    for ej, ti, tk in product(range(0, ebins), range(0, cbins), range(0, cbins)):
        ec_j = ej * cbins
        dcdP[ti, ec_j+tk] = -NE_F_R[ej] * Mij[ej, ti] * n_c_prev[tk]
    return dcdP

def new():
    dcdP = np.zeros((cbins, cbins * ebins))
    # (ti, ec_j + tk) elements
    tk = np.arange(0, cbins)
    for ej in np.arange(0, ebins):
        A = np.outer(-NE_F_R[ej] * Mij[ej, :], n_c_prev)
        for ti in np.arange(0, cbins):
            dcdP[ti, ej * cbins + tk] = A[ti, tk]
    return dcdP

np.testing.assert_array_equal(original(), new())
```

</details>

<br>

Do you think there might be some edge cases the example tests in `test_unfold.py` are not catching?

**Comment by zhampel** [comment]
No, I think what you've done for testing is sufficient. So long as you were getting compatible results, I'm good with the changes you've made.

**Comment by jrbourbeau** [comment]
Thanks for reviewing @zhampel :)

**Pull request merged**
