### PR TITLE
[DOC] reorganize examples

### LINKED ISSUE #94: Showcase example notebooks
It'd be nice to have more integration with [the notebook examples][1]. This would (likely) include

* integrating the examples into the docs as static HTML pages
* integrating with Binder for executable notebooks

[1]:https://github.com/jrbourbeau/pyunfold/tree/bf1ce87a59e23e1fc30854e96aa4c63d0380bdf0/docs/source/notebooks

### PR DESCRIPTION
**Pull request by stsievert**
Closes #94.

Promoted examples to go right below installation:

screen shot 2018-09-03 at 10 29 54 am

### CODE REVIEW

**Comment by fzeiser** [comment]
What a good idea. However, I would slightly reword the introduction. It is one unfolding technique used, however there are different examples of how it is implemented.

**Comment by jrbourbeau** [comment]
Thanks for the PR @stsievert, the re-organized layout looks great! 

To @fzeiser's point, we can probably safely remove the "There are several advanced...these include:" text between the new "Examples" heading and the list of example notebooks.

**Comment by stsievert** [comment]
> we can probably safely remove the "There are several advanced...these include:" text between the new "Examples" heading and the list of example notebooks.

D'oh.

**Review by jrbourbeau — APPROVED** [review]
LGTM. Thanks @stsievert!

**Pull request merged**
